module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.ts?(x)', '**/?(*.)+(spec|test).ts?(x)'],
  testPathIgnorePatterns: [
    '/node_modules/',
    // Exclude legacy test files that use process.exit() - run these separately with ts-node
    'src/services/sessions.test.ts',
    'src/services/stats-simple.test.ts',
    'src/services/achievements.test.ts',
    'src/utils/xp.test.ts',
    'src/commands/groups/__tests__/group.test.ts',
    'src/commands/groups/__tests__/joingroup.test.ts',
    'src/commands/groups/__tests__/leavegroup.test.ts',
    'src/commands/groups/__tests__/groupadmin.test.ts',
    'src/commands/groups/__tests__/creategroup.test.ts',
    'src/__tests__/groups.integration.test.ts',
    'src/services/groups.test.ts',
    'src/services/stats.test.ts',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'json'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.test.ts',
    '!src/**/*.test.tsx',
    '!src/**/*.spec.ts',
    '!src/bot.ts',
    '!src/bot.legacy.ts',
    '!src/services/sessions.test.ts',
    '!src/services/stats-simple.test.ts',
    '!src/utils/xp.test.ts',
  ],
};
