[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "expat",
  "cairo",
  "pango",
  "glib",
  "gtk3",
  "gdk-pixbuf",
  "libdrm",
  "libxcb",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXcursor",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXrandr",
  "xorg.libXrender",
  "xorg.libXtst",
  "xorg.libxkbcommon",
  "mesa",
  "at-spi2-atk",
  "at-spi2-core",
  "fontconfig",
  "freetype",
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
